### ISSUE TITLE
Enable templating for keys

### ISSUE THREAD

**Issue by t00f** [curran/json-templates#2]
It would be useful in the future to be able to mark some keys as template.

```javascript
filters: {
    "{{direction:source}}" : "myValue"
}
```

That way, we should be able to change the direction to `destination` for instance.

**Comment by curran** [comment]
Interesting idea!

**Comment by curran** [comment]
Implemented in #3 . Thanks @t00f ! Closing.

I made a few minor changes in #4 you may want to review.
